### ISSUE TITLE
Right clicking while using a siren does not deselect prior mode

### ISSUE THREAD

**Issue by noble-ux** [photonle/Photon#112]
## Expected Behaviour
Right clicking should toggle between siren modes on the UI.

## Actual Behaviour
Right clicking continually enables siren modes on the UI, and then disables them once they are selected again when the siren is disabled.

## Error Messages (if any)
N/A

## Steps to Reproduce

  1. Enable siren
  2. Right click to toggle through modes. Each mode will select but will not deselect
  3. Disable siren
  4. Right click to toggle through modes. Each mode will deselect.

## Details
- Source (Workshop / Github): Github, only dev branch
- Garry's Mod Beta/Branch (if not standard): N/A

**Comment by creator2013** [comment]
https://github.com/photonle/Photon/commit/c521ae6ac28b694d4a216a8cf4da4c21d8b1a52c
