### ISSUE TITLE
Option To Disable Primary Siren

### ISSUE THREAD

**Issue by Moonlight-Howl1** [photonle/Photon#114]
## Feature
A similar option with the secondary siren, in which you can have nothing selected. But instead have the option available for the primary siren as well.

## Use Case
I've noticed when a vehicles normally doesn't have an active primary siren, it'll still show a siren selected, but the UI for Photon is smaller, so it could be argued a person would be able to see more on-screen.

## Alternatives
One alternative would be not to press R, but in my opinion, it would be more satisfying if I were able to press R and no sirens activate.

**Comment by creator2013** [comment]
https://github.com/photonle/Photon/commit/3746ce16bd11528de12c6c2071953515d48bafe4
