### ISSUE TITLE
Add it or I'll demote you down to probationary user.

### ISSUE THREAD

**Issue by GermanDude-ger** [photonle/Photon#121]
## Feature
Add Scale = Vector function to components

## Use Case
Uhm, like for cars n' stuff? 

## Alternatives
None. I wouldn't suggest shit if there was an alternative, would I?

## Context
![Desktop Screenshot 2019 12 19 - 16 48 14 32](https://user-images.githubusercontent.com/59023102/71204338-37881b80-22a0-11ea-86ae-0777599ebcc1.png)
Look at screenshot. You did? Perfect. This is only doable with fucking Scale = Vector, otherwise the Freedom would look horrid.

**Comment by JoshPiper** [comment]
closed by request
