### ISSUE TITLE
EQ2B Siren

### ISSUE THREAD

**Issue by epickilljoy** [photonle/Photon#127]
Absolutely love Photon and love the new update with the addition of the Q siren and the updated EQ2B siren, However would it be possible to have the current EQ2B siren labeled as another Q siren and the old EQ2B siren put in its place.

For example in Federal
EQ2B (old EQ2B siren)
EQ (current EQ siren)
EQ2 (current EQ2B siren)

## Use Case
This would make it sound more realistic with Ambulances as most ambulances dont use a mechanical Q siren and instead use the Electric Q2B siren.

**Comment by JoshPiper** [comment]
Heya, we're no longer looking for new sirens. I'll close this, but feel free to drop it in the Photon discord ideas channel.
