### ISSUE TITLE
The invite to the discord expiered

### ISSUE THREAD

**Issue by xcryingryanx** [photonle/Photon#132]
The invite is expired please make a new invite I can't join the discord

**Comment by xcryingryanx** [comment]
Please make a new invite it expired

**Comment by xcryingryanx** [comment]
Also I can't get the Express Creator or Editor because I want to make a police car but I can't without those.

**Comment by xcryingryanx** [comment]
@SentryGunMan 
Can you send me the link for the express editor and Creator?

**Comment by SuperMighty1** [comment]
https://discord.gg/tUkHSFC

**Comment by creator2013** [comment]
https://discord.gg/xaCtdrq
https://discord.gg/c2uRHtY
https://discord.gg/tUkHSFC
https://discord.gg/PgGGwx8
https://discord.gg/uuxdtbh

**Comment by xcryingryanx** [comment]
It says its invalid

**Comment by creator2013** [comment]
What is your discord tag

**Comment by xcryingryanx** [comment]
SUBTOMYYTCHANNLE12loa#9937

**Comment by xcryingryanx** [comment]
![HELP](https://user-images.githubusercontent.com/40190333/74110519-204c0880-4b42-11ea-8fe5-84d04d719b07.PNG)

**Comment by xcryingryanx** [comment]
SUBTOMYYTCHANNLE12loa#9937

**Comment by creator2013** [comment]
The links are not invalid, you are just in too many servers

**Comment by xcryingryanx** [comment]
ohhhhhh

**Comment by xcryingryanx** [comment]
There we go

**Comment by xcryingryanx** [comment]
I'm in

**Comment by creator2013** [comment]
move to #support
