### ISSUE TITLE
In-Vehicle Dome Light 

### ISSUE THREAD

**Issue by ANorthCanadianFriend** [photonle/Photon#133]
## Feature
A red and white dome light that you can turn on/off and switch between W 

and R in the front between the drivers seat and passanger seat.

## Use Case
Used for lighting inside of the vehicle in dark areas, can be used for rp situations if you are writing a ticket inside your vehicle and you need light. 

![181019_UPD Academy_Ridealong0030-2](https://user-images.githubusercontent.com/55059204/74488266-7ee0f180-4e76-11ea-805f-6bafd569ddda.jpg)
![SJM-L-COPCLASS-0511-1](https://user-images.githubusercontent.com/55059204/74488269-80aab500-4e76-11ea-9184-6f5add994b7c.jpg)
![2015-ford-police-intercep-12](https://user-images.githubusercontent.com/55059204/74488270-81dbe200-4e76-11ea-9bca-958365fae2f5.jpg)

**Comment by DatedGore** [comment]
cool

**Comment by JoshPiper** [comment]
Heya, we're no longer looking for new components. I'll close this, but feel free to drop it in the Photon discord ideas channel.

**Comment by DatedGore** [comment]
uh ok i dont remember what this is about tbh

>
