### ISSUE TITLE
HUD keeps size when changing game resolution

### ISSUE THREAD

**Issue by dkDeMKN** [photonle/Photon#135]
## Expected Behaviour
HUD will change to a size that fits the resolution

## Actual Behaviour
HUD (in this instance) kept its small size when going from a small resolution to the native resolution in windowed mode to borderless fullscreen.

## Error Messages (if any)
None

## Steps to Reproduce

  1. Enter windowed mode in a lower resolution than native
  2. Enter borderless fullscreen in native resolution
  3. Result: HUD is small and slightly up and to the left of the bottom right corner.

## Details
- Source (Workshop / Github):	
- Garry's Mod Beta/Branch (if not standard):

**Comment by JoshPiper** [comment]
We'd need to look into this, see if there's a way of detecting resolution changes without hooking into the global panel.

**Comment by creator2013** [comment]
https://wiki.facepunch.com/gmod/GM:OnScreenSizeChanged
Added on 2020.04.29. Feature can be added in version 75

**Comment by jooiiee** [comment]
![text?](https://user-images.githubusercontent.com/2373478/87822679-2b822d80-c872-11ea-8a44-375916e7880a.jpg) Photo of bug after window changes resolution. Thanks for reporting Valor so I don't have to.

**Comment by noble-ux** [comment]
HUD would need to be rewritten in rem or em units to properly scale up. Not sure I'd label this as a bug however.

**Comment by JoshPiper** [comment]
No, the HTML keeps its old size / position when the game resizes @Noble-N9?
![image](https://user-images.githubusercontent.com/32164094/91426428-6d7c9700-e854-11ea-987c-74480be8db44.png)
If the purple box is the old resolution, then the game resizes to the screenshot resolution, the HUD doesn't resize / move like it should.

**Comment by noble-ux** [comment]
I see now, I thought the issue was for just the overall sizing of the element remaining constant regardless of what screen resolution the user was on.
