### ISSUE TITLE
PI Sound Plays even if BlinkLeft isn't defined

### ISSUE THREAD

**Issue by JoshPiper** [photonle/Photon#143]
## Expected Behaviour
When no turn signals are defined, no sound plays.

## Actual Behaviour
Sound Plays

## Details
- Source (Workshop / Github): Workshop
- Garry's Mod Beta/Branch (if not standard): -

**Comment by creator2013** [comment]
https://github.com/photonle/Photon/commit/6884ab06d23c1084ac144790f8980d65e976e0f4
