### ISSUE TITLE
COMPONENT.Required has no usage

### ISSUE THREAD

**Issue by creator2013** [photonle/Photon#147]
## Expected Behaviour
COMPONENT.Required helps players (with default TDM components / on servers) to find the addon they need for a component to work

## Actual Behaviour
COMPONENT.Required has absolutely no use

## Details
- Source (Workshop / Github):  Github v74

**Comment by JoshPiper** [comment]
I suggest we have a simple way of handling this.

Required = "workshopid"
Model = "whatever"

If the model isn't mounted, add required to a list of warnings.
