### ISSUE TITLE
Numpad+/- for finding Light Index's 

### ISSUE THREAD

**Issue by OfficialImBad** [photonle/Photon#152]
## Expected Behaviour
Show Light Index Number for the Lightbar

## Actual Behaviour
Nothing happens

Gif to show Problem - If you watch Gmod in the Right Hand Corner you can see it doesn't change, if you also look at the corsair software on the right you can see that I am pressing numpad +/- 

https://gyazo.com/c5cba5a4bb5fe0f7e6c4a1489e6ea6ad

## Error Messages (if any)
None

## Steps to Reproduce

  1. Load Gmod Up into gm_flatgrass
  2. Spawn in a development car
  3. Toggle Debug Mode
  4. Press Numpad +/- and nothing changes.

## Details
- Source (Workshop / Github): Workshop	
- Garry's Mod Beta/Branch (if not standard): Normal

**Comment by creator2013** [comment]
Issue was caused on users behalf. User had to set the debug target while sitting in the car or while looking at it.
