### ISSUE TITLE
Patterns automatically switching to the third sequence(CODE 3 / STAGE 3) on the car whenever I toggle the manual siren while the auto siren is in action.

### ISSUE THREAD

**Issue by rebss** [photonle/Photon#208]
Before I begin, I didn't know what to label this since I remember creator telling me that this was actually a feature in the code so I couldn't label it as a "bug" because it was intentional but it's also not like adding a new feature from scratch so I couldn't pick "feature" either, that's why I left it blank I hope It's not a big issue.

As for my problem;

Although I call this an "issue", I reckon most people wouldn't even care about this being a thing in the first place, let alone being annoyed by it, however, I can't really speak for everybody but for Turkish Photon users, this becomes a huge problem especially in pursuits, responds and all kinds of situations because our lightbars don't have an automatic pattern switching system when the manual siren is toggled. The only way you can change the pattern of the lightbar and all of the lights on the car is manually switching from one pattern to another via the remote control, changing the siren modes won't do anything to the lights itself. Also, I left an attached video as a link down below for more clarification of the issue.

https://user-images.githubusercontent.com/46074204/216919519-0fdecdd2-0926-4ea2-91e0-9ac3e4c50039.mp4

I'm not asking for a complete removal of this feature by any means possible but I think It would be really nice if there was an option in the Photon settings to toggle this on/off for the players or the server completely. I think that, even if most people wouldn't see this as a problem, countries like Turkey have much simpler systems when it comes to emergency lighting so some people like me would just prefer a more basic system with no interruptions such as this.

**Comment by ischmal** [comment]
Yeah, so it's part of the "ALERT" feature and is intentional, but I see what you're saying. Making it optional on a per-user/per-component basis shouldn't be an issue, so I'll see what I can do.

**Comment by rebss** [comment]
Thanks for the response. I actually asked about this before in the Photon Discord and evantually talked to creator in private about it. He told me he had other projects to work on and I didn't want to disturb him with another message after that, thats why I submitted it in here too.
![image](https://user-images.githubusercontent.com/46074204/216935803-847e36f5-95c6-47f5-bf13-5a98ab0e5319.png)

**Comment by ischmal** [comment]
The development branch has been updated to support selectively disabling the "Alert Mode" pattern changing on a per-vehicle basis.

To achieve this, add the following code block to your vehicle file (or [see example](https://pastebin.com/8v7bpfXw)):
```
EMV.Attributes = {
	DisableAlertPatterns = true
}
```

By default, `DisableAlertPatterns` is treated as `false`, so you have to opt-in, but this should solve the problem you're having.

**Comment by rebss** [comment]
Thank you so much, I will try it right now and tell you the results.

**Comment by rebss** [comment]
I just tested it and it seems to have fixed the problem. I only have one question though; so, I'm planning on adding that code to all of my photon vehicles but will it cause any issues with the workshop branch if I change all of them right now or should I wait until the workshop branch gets updated?

**Comment by ischmal** [comment]
There shouldn't be any compatibility issues, so yeah, you can update them now and not worry about breaking anything.

**Comment by rebss** [comment]
Alright then, that was the only question left on my mind. Thank you again for helping me with this one.
