### ISSUE TITLE
Component Library No Longer Available

### ISSUE THREAD

**Issue by isaiahwiesner** [photonle/Photon#219]
Hello,

I have watched this video by Schmal (https://youtu.be/wbvr2E3FQhk) before and made Photon cars in the past, however, the component library I have always used linked in the description (https://photon.lighting/wiki/index.php) is no longer available. If there is a different reference of a fix available please let me know.

**Comment by JoshPiper** [comment]
https://github.com/photonle/Photon/wiki/Components
