### ISSUE TITLE
64x bit selections broken

### ISSUE THREAD

**Issue by JoshPiper** [photonle/Photon#22]
## Expected Behaviour
Set selections from user selections.

## Actual Behaviour
Error

## Error Messages (if any)
```
[ERROR] addons/photon/lua/autorun/photon/cl_emv_net.lua:156: attempt to call field 'gfind' (a nil value)
  1. ApplyAutoSkin - addons/photon/lua/autorun/photon/cl_emv_net.lua:156
   2. Photon_ApplyEquipmentConfiguration - addons/photon/lua/autorun/photon/cl_emv_meta.lua:907
    3. DoClick - addons/photon/lua/autorun/photon/cl_photon_context.lua:302
     4. OnMouseReleased - lua/vgui/dlabel.lua:234
      5. unknown - lua/vgui/dmenuoption.lua:77
```

## Steps to Reproduce

  1. Run 64 bit.
  2. Make user selection.
  3. Select selection.

## Details
- Source (Workshop / Github): Github
- Garry's Mod Beta/Branch (if not standard): x64

**Comment by sohpeach** [comment]
i've released a patch for gmod's x86-64 branch that should fix this

**Comment by JoshPiper** [comment]
Beauty, I'll test and close if it's fixed.
