### ISSUE TITLE
Component bodygroups not changing

### ISSUE THREAD

**Issue by SuperMighty1** [photonle/Photon#27]
## Expected Behaviour
Bodygroups of lightbars being able to change the glass colour.

## Actual Behaviour
Bodygroups not changing the lightbars glass colour, appearing as clear.

## Error Messages (if any)
None.

## Steps to Reproduce

  1.  Download or use a component that has a colored glass variant and set it to one of the colours
  2.  Add the lightbar to the vehicles code
  3.  Spawn the vehicle

## Details
- Source (Workshop / Github):	Github
- Garry's Mod Beta/Branch (if not standard): Standard public build.

**Comment by JoshPiper** [comment]
See https://steamcommunity.com/sharedfiles/filedetails/?id=1418325844 for an example lightbar.

**Comment by creator2013** [comment]
Pushed a fix to the development branch https://github.com/photonle/Photon/commit/c48de6558b0908b92f53fd72c98f7b2c29560e4e
