### ISSUE TITLE
Whelen Century Lightbar

### ISSUE THREAD

**Issue by ANorthCanadianFriend** [photonle/Photon#28]
Hello, I was wondering if the new Whelen Cenator Series lightbar could please be added to Photon? the RCMP is switching there cruisers with the new bar and I wanted to add it to my vehicle. 
![ce4rrbb-34](https://user-images.githubusercontent.com/55059204/65710704-c5ad8680-e050-11e9-9f14-35ad11ce5615.jpg)

**Comment by JoshPiper** [comment]
Heya, we're no longer looking for new components. I'll close this, but feel free to drop it in the Photon discord ideas channel.
