### ISSUE TITLE
Ablity to go backwards with the Sirens.

### ISSUE THREAD

**Issue by LilGothPuppy** [photonle/Photon#32]
## Feature
Like, we have the button to move the siren forward; having an option to go backwards.

## Use Case
Saying if you switch to a Phaser and want to go back to a Yelp (the one before), you'd have to manually go back to the Wail (or hit 1), and then switch to the Yelp. - I know 1,2,3,4 are bound to the siren change; however, if you have VCmod installed, it isn't possible to do it that way, because you end up changing seats.
*Example Met Siren*

## Alternatives

I'm not sure you could make an Alternative tbh

## Context
N/A

**Comment by ANorthCanadianFriend** [comment]
I like that idea alot.

**Comment by JoshPiper** [comment]
Fixed by #90.
