### ISSUE TITLE
Primary and Secondary sirens in photon code.

### ISSUE THREAD

**Issue by DatedGore** [photonle/Photon#33]
## Feature
In the current version of photon you can only have a primary siren in the photon code. But in game you can have two? This doesnt make sense. This needs to be added. Maybe have a Siren = 1 and a Siren2 = 4

## Use Case
It would imrpove the siren feature. This would also make it to where you can add two sirens in the photon code

**Comment by creator2013** [comment]
You can already set the secondary siren with `EMV.AuxiliarySiren`
