### ISSUE TITLE
Base Photon Components Give Errors

### ISSUE THREAD

**Issue by Nardoras** [photonle/Photon#39]
## Expected Behaviour
Vehicle spawns with the component

## Actual Behaviour
Vehicle spawns without the component. The rest of the vehicle's lights works, an error message is given in the console, but the yellow error popup does not appear.

## Error Messages (if any)
"[Photon] Auto component: Whelen Ion Split was not found in the library. Requested in: NVFD Duty 21."
"[Photon] Auto component: Federal Signal Viper Dual was not found in the library. Requested in: NVFD Duty 21."
-- Most of the components from Schmal's Ford Police Interceptor Utility 2016 have this issue, I used this vehicle to test that it wasn't my vehicle's lua creating the issue.
## Steps to Reproduce

  1. Forgot to add "AddCSLuaFile()" to a custom component
  2. Recieved same error

## Details
- Source (Workshop / Github):	Workshop
- Garry's Mod Beta/Branch (if not standard): Standard

**Comment by Nardoras** [comment]
Added a component that turned out to be another bugged base component, TDM Rear Interior Lightbar. Recieved error,

[Photon: Lighting Engine] lua/autorun/photon/cl_emv_meta.lua:701: attempt to index a nil value
  1. Photon_ScanEMVProps - lua/autorun/photon/cl_emv_meta.lua:701
   2. DrawCarLights - lua/autorun/photon/cl_emv_init.lua:59
    3. v - lua/autorun/photon/cl_emv_init.lua:73
     4. unknown - lua/includes/modules/hook.lua:84

The error continued popping up until the vehicle was respawned and when trying to use the bar afterwards it returned to,

[Photon] Auto component: TDM Rear Interior Lightbar was not found in the library. Requested in: State Trooper 15 Charger.

**Comment by JoshPiper** [comment]
Sorry for the delay @Nardoras, which vehicles were you using that this happened with?

**Comment by JoshPiper** [comment]
Closed, unable to reproduce error.
