### ISSUE TITLE
[PreRelease Beta] Several photon functions are not working

### ISSUE THREAD

**Issue by creator2013** [photonle/Photon#46]
## Problem 1
Hud disappears as soon as you press T, B or X.

## Problem 2
If you leave a vehicle when the lights are active the current pattern freezes / current section stays on.

## Problem 3
If you reproduce "Problem 2" and despawn the vehicle, the props of the vehicle won't despawn.

## Details
- Source (Workshop / Github): Github
- Garry's Mod Beta/Branch (if not standard): 64bit Beta

I also think that the hud is more bold in the beta.

**Comment by creator2013** [comment]
According to Lily this is the same case for the chromium beta

**Comment by SuperMighty1** [comment]
Same case for the pre release branch.

Also in addition to Problem 2; if you leave the vehicle and wait approx 5 mins and get back in the lights will not continue.

**Comment by SuperMighty1** [comment]
When using the console command photon_stick  in a vehicle only the hud problem remains.

**Comment by JoshPiper** [comment]
Possible fix in #66
