### ISSUE TITLE
HUD Opacity is on/off, doesn't fade.

### ISSUE THREAD

**Issue by JoshPiper** [photonle/Photon#59]
## Expected Behaviour
HUD opacity 150 is semi visible.

## Actual Behaviour
It only turns on or off

## Error Messages (if any)
-

## Steps to Reproduce

  1.  set hud opacity to 150
  2.  set hud opacity to 0
  3.  set hud opacity to 255

## Details
- Source (Workshop / Github): Workshop
- Garry's Mod Beta/Branch (if not standard): stable

**Comment by JoshPiper** [comment]
Very weird, none of the ways of changing it (material alpha, surface.setalphamultipler or surface.setcolor) seem to work.

**Comment by noble-ux** [comment]
https://codepen.io/nkruse/pen/PoodNQL
