### ISSUE TITLE
D&R Intimidator has no Airhorn anymore

### ISSUE THREAD

**Issue by ANorthCanadianFriend** [photonle/Photon#65]
## Expected Behaviour
Sound

## Actual Behaviour
No sound

## Steps to Reproduce

  1. 
  2. 
  3. 

## Details
- Source (Workshop / Github):	
- Garry's Mod Beta/Branch (if not standard):

**Comment by creator2013** [comment]
Fixed in https://github.com/photonle/Photon/commit/3950aaae5ca5b2ee8c33644f54a2665484eb6477
