### ISSUE TITLE
Manual and Horn icons override.

### ISSUE THREAD

**Issue by JoshPiper** [photonle/Photon#67]
## Expected Behaviour
When pressing horn and manual siren keys, both HUD icons show.

## Actual Behaviour
Only one shows.

## Error Messages (if any)
-

## Details
- Source (Workshop / Github): GitHub - DTVar Fix.
- Garry's Mod Beta/Branch (if not standard): x64

**Comment by creator2013** [comment]
https://github.com/photonle/Photon/commit/38cacd26802a9743fba8aca7cdd62d2b45c5cc40
