### ISSUE TITLE
PI lighting delayed

### ISSUE THREAD

**Issue by SuperMighty1** [photonle/Photon#68]
## Expected Behavior
When breaking in a vehicle they should appear almost instantly

## Actual Behavior
Brake PI lighting takes a good 3-5 seconds to appear, same for reverse lights.

Example : https://youtu.be/ONHlow-e-04
## Error Messages (if any)
N/A

## Steps to Reproduce

  1.  Download a vehicle with PI lighting, press spacebar a few times
  2. 
  3. 

## Details
- Source (Workshop / Github): V72 release	
- Garry's Mod Beta/Branch (if not standard): None

**Comment by creator2013** [comment]
For devs: sv_photon_hooks.lua:29
`timer.Create("Photon.RunScan", 1, 0, function()
	Photon:RunningScan()
end)`

**Comment by JoshPiper** [comment]
Might be worth seeing if we can get a listener type setup going so PI switches on command input, not just on a scan every X time.

**Comment by LilGothPuppy** [comment]
Did you know that there is a delay with Photon PI Lights?
