### ISSUE TITLE
Configurations not working

### ISSUE THREAD

**Issue by sammyfc** [photonle/Photon#69]
## Expected Behaviour
To be able to see configs and make new configs.

## Actual Behaviour
Cannot see any configs nor make new ones or see the pre-made ones (I tested on Explorer and Charger)

## Steps to Reproduce

  1. Spawn a police vehicle
  2. Check for configs in C  menu
  3. 

## Details
- Source (Workshop / Github): 	
- Garry's Mod Beta/Branch (if not standard): x64

**Comment by creator2013** [comment]
Were you inside the vehicle when you tried to use the context menu?

**Comment by sammyfc** [comment]
Yes

**Comment by creator2013** [comment]
I just tested it with stable and x64 and on both versions I can see the "Configurations" option in the context menu of Schmal's FPIU.

**Comment by sammyfc** [comment]
I'm not sure why it isn't working then? Because I have tried to make new
ones and they don't show either. I will try again later and see if it is
resolved

**Comment by sammyfc** [comment]
Still doesnt work for me on any cars.

**Comment by creator2013** [comment]
Have you tried to disablle all addons except Photon and Schmals FPIU? If not: do that and see if it works.

**Comment by sammyfc** [comment]
I asked Doctor Internet in LL (I think he is a deleveloper for photon) and
he said it is a problem with Limelight itself not photon

**Comment by JoshPiper** [comment]
Note: Add a way of adding configuration support from the EMVU.Override...

**Comment by JoshPiper** [comment]
Fixed in #73
