### ISSUE TITLE
 I personally think that it would be interesting to let the siren going on while we are out of the vehicules. Or to put an option in the Options menu of photon for admins to enable it or disabled that option... What do you think of that?

### ISSUE THREAD

**Issue by MathisMake** [photonle/Photon#83]
## Use Case
When this would be used / what it would improve.

## Alternatives
Other ideas that would work in place.

**Comment by creator2013** [comment]
Incorrect use of GitHub Issues
- The title should be short summary of the request
- The purpose of the template has not been used
