### ISSUE TITLE
lua seems not working

### ISSUE THREAD

**Issue by Burtjack** [photonle/Photon#87]
## Error Messages (if any)
[Photon LE (Version 70)] lua/autorun/photon/sh_emv_helper.lua:367: attempt to index local 'autoData' (a nil value)
1. GetProps - lua/autorun/photon/sh_emv_helper.lua:367
2. Photon_SetupEMVProps - lua/autorun/photon/cl_emv_meta.lua:586
3. Photon_RemoveEMVProps - lua/autorun/photon/cl_emv_meta.lua:661
4. Photon_ScanEMVProps - lua/autorun/photon/cl_emv_meta.lua:670
5. DrawCarLights - lua/autorun/photon/cl_emv_init.lua:59
6. v - lua/autorun/photon/cl_emv_init.lua:71
7. unknown - lua/includes/modules/hook.lua:84

## Steps to Reproduce

  1. 
  2. 
  3. 

## Details
- Source (Workshop / Github):	
- Garry's Mod Beta/Branch (if not standard):

**Comment by creator2013** [comment]
Please provide more information.
- When do you get this error?
- Which lua do you mean?

You can also join our Discord server where we can provide you support.

+ It seems like you are using an older version of photon. Try to update the addon.

**Comment by creator2013** [comment]
No more information received, closing issue.
Try to update to the newest photon version and check the console for details. If you still have a problem feel free to create a new issue or join the discord server.
