### ISSUE TITLE
Photon GUI

### ISSUE THREAD

**Issue by Cloudofnothing** [photonle/Photon#9]
I was using photon for awhile then all of a sudden my screen to help me see when I can change my lightbar to a different code, when I can change my siren to a different sound, I been trying to look how I can get it back but there is nothing on it so I hope you know what I am talking about and I hope you can help me.

**Comment by LauritzT** [comment]
Can you provide screenshots or more detail? I've never heard of that before.

**Comment by TheSenDest** [comment]
test

**Comment by Cloudofnothing** [comment]
[](http://steamcommunity.com/sharedfiles/filedetails/?id=680539834) As you can see I am in my car but I can't see my GUI @LauritzT

**Comment by Cloudofnothing** [comment]
Nvm i fixed the problem
