### ISSUE TITLE
Ion V Improper Code

### ISSUE THREAD

**Issue by Nardoras** [photonle/Photon#94]
## Expected Behaviour
N/A?

## Actual Behaviour
M1/2/3 stages are set to use "auto_ion_v" and ALERT to use "auto_ion."
Both Sections and Patterns are missing these, only having "auto_whelen_linz6" listed.

## Steps to Reproduce

  1. View lua code for the Whelen Ion V

## Details
- Source - Github	
- Garry's Mod - Standard

**Comment by SuperMighty1** [comment]
Fixed https://github.com/photonle/Photon/commit/6ac28f80759160ab93659472df4914e65ac9a40d
