### ISSUE TITLE
Photon_Stick - Admin button that enables it globally for every car/person.

### ISSUE THREAD

**Issue by LilGothPuppy** [photonle/Photon#97]
## Feature
A button under the Photon options that allows admins to enable/disable the "Photon_Stick" effect on every single Photon vehicle and for every player with ease. Without having to open the console and type it in every time.

## Use Case
Realism...

## Alternatives
Just make it turned on 24/7 with no option to turn it off 😂 

## Context
Bitch.

**Comment by creator2013** [comment]
https://github.com/photonle/Photon/commit/31a15f6b3f1bcf3608fbc01c5056f86614bfe164
